### ISSUE TITLE
Doesn't build on OSX due to --gc-sections

### ISSUE THREAD

**Issue by sr105** [nmenon/omap-u-boot-utils#4]
$ ld -v
@(#)PROGRAM:ld  PROJECT:ld64-134.9
configured to support archs: armv6 armv7 armv7s i386 x86_64
LTO support using: LLVM version 3.1svn, from Apple Clang 4.1 (build 421.11.66)

Workaround:

--- makefile.orig   2013-02-12 08:51:28.000000000 -0500
+++ makefile    2013-02-12 08:49:39.000000000 -0500
@@ -99,7 +99,7 @@ CFLAGS=-Wall -O3 -Iinclude -Ilib/lcfg
 LDFLAGS=

 CFLAGS+=-fdata-sections -ffunction-sections
-LDFLAGS+=-Wl,--gc-sections -Wl,--print-gc-sections -Wl,--no-print-gc-sections
+#LDFLAGS+=-Wl,--gc-sections -Wl,--print-gc-sections -Wl,--no-print-gc-sections
 LDFLAGS_USB=-lusb

 CROSS_CC ?=$(CROSS_COMPILE)gcc

**Comment by akemnade** [comment]
found a chance to test and inspect it on OSX, will post a fix after my pull req (#7) is processed for merging simplicity.

**Comment by nmenon** [comment]
Thanks. Looking forward for a PR with a fix for this.

**Comment by nmenon** [comment]
Thanks for fixing via https://github.com/nmenon/omap-u-boot-utils/pull/8 -> merged.
